//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.fenceit.ui.adapters;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import com.fenceit.R.id;
import com.fenceit.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class LocationMapInfoWindowView_
    extends LocationMapInfoWindowView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public LocationMapInfoWindowView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        titleText = ((TextView) findViewById(id.markerInfoWindow_title));
        optionalText = ((TextView) findViewById(id.markerInfoWindow_optional));
        descriptionText = ((TextView) findViewById(id.markerInfoWindow_description));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.marker_info_content, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static LocationMapInfoWindowView build(Context context) {
        LocationMapInfoWindowView_ instance = new LocationMapInfoWindowView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
