//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.fenceit.ui.helpers;

import android.app.Activity;
import android.content.Context;
import android.location.Address;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import com.fenceit.ui.CoordinatesMapActivity;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class LocationMapSearchTask_
    extends LocationMapSearchTask
{

    private Context context_;
    private Handler handler_ = new Handler();

    private LocationMapSearchTask_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        if (context_ instanceof CoordinatesMapActivity) {
            activity = ((CoordinatesMapActivity) context_);
        }
    }

    public static LocationMapSearchTask_ getInstance_(Context context) {
        return new LocationMapSearchTask_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void updateUI(final Address result) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    LocationMapSearchTask_.super.updateUI(result);
                } catch (RuntimeException e) {
                    Log.e("LocationMapSearchTask_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void searchInBackground(final String toSearch) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    LocationMapSearchTask_.super.searchInBackground(toSearch);
                } catch (RuntimeException e) {
                    Log.e("LocationMapSearchTask_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
